### ISSUE TITLE
Build fails on latest master

### ISSUE THREAD

**Issue by bradleystachurski** [elsirion/fedimint-observer#13]
`just b` fails on latest master (https://github.com/elsirion/fedimint-observer/tree/09f93e68534dcdc84fa69380a15ca5c994787b3d).

```
error[E0433]: failed to resolve: could not find `Builder` in `task`
   --> /home/nix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fedimint-core-0.3.0-rc.3/src/task.rs:462:26
    |
462 |             tokio::task::Builder::new()
    |                          ^^^^^^^ could not find `Builder` in `task`
```

This failed locally when using `nix develop` from the root of this repo and also from a recent commit from `fedimint/fedimint` (https://github.com/fedimint/fedimint/tree/636282449edda8f5651e240a01326e28bb99ceae).

**Comment by elsirion** [comment]
Looks related to https://github.com/fedimint/fedimint/pull/5051
